# Generated by Django 3.2 on 2021-04-25 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_request_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_detail',
            name='renew_till',
            field=models.DateField(default=models.DateField(default=datetime.datetime(2021, 5, 2, 16, 7, 35, 570333, tzinfo=utc))),
        ),
        migrations.AlterField(
            model_name='request_detail',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 16, 7, 35, 570333, tzinfo=utc)),
        ),
    ]
