# Generated by Django 3.2 on 2021-04-25 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210425_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_detail',
            name='renew_till',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 16, 8, 40, 796667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request_detail',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 16, 8, 40, 796667, tzinfo=utc)),
        ),
    ]
