# Generated by Django 3.2 on 2021-04-25 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210425_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_detail',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 16, 12, 5, 56434, tzinfo=utc)),
        ),
    ]
